name: example
description: A example of how to use the carp_core library
publish_to: 'none'
version: 0.40.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  carp_serializable:
    path: ../../carp_serializable/
  carp_core:
    path: ../

dev_dependencies:
