name: carp_context_package
description: CARP context sampling package. Samples location, mobility, activity, weather, air-quality, and geofence.
version: 0.31.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_context_package

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
 
  carp_core: ^0.31.0
  carp_mobile_sensing: ^0.31.0
 
  json_annotation: ^4.0.1
  permission_handler: '>=8.1.0 <8.2.0'
  weather: ^2.0.1
  air_quality: ^2.0.0
  activity_recognition_flutter: ^4.0.3
  openmhealth_schemas: ^0.2.1
  mobility_features: ^3.0.0
  location: ^4.3.0  # also handles location in the background

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/
#  openmhealth_schemas:
#    path: ../../../openmhealth_schemas/

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  pedantic: ^1.11.1        # For pedantic Dart linter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  test: ^1.17.9

# The following section is specific to Flutter.
flutter:
