name: carp_context_package
description: CARP context sampling package. Samples location, mobility, activity, weather, air-quality, and geofence.
version: 0.33.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_context_package

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
 
  # carp_core: ^0.33.0
  # carp_mobile_sensing: ^0.33.0
 
  json_annotation: ^4.3.0
  permission_handler: ^9.2.0  
  weather: ^2.0.1
  air_quality: ^2.0.0
  flutter_activity_recognition: ^1.3.0
  openmhealth_schemas: ^0.2.1
  mobility_features: ^3.1.0
  location: ^4.3.0  # also handles location in the background

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  carp_core:
    path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  # openmhealth_schemas:
  #   path: ../../../openmhealth_schemas/
  # mobility_features:
  #   path: ../../../../flutter-plugins/packages/mobility_features/

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  pedantic: any        # For pedantic Dart linter
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
