name: carp_apps_package
description: Apps sampling package for the CARP Mobile Sensing framework (Android only).
version: 0.30.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_apps_package
author:  CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carp_core: ^0.30.0
  carp_mobile_sensing: ^0.30.0
  app_usage: ^2.0.0
  device_apps: ^2.1.1
  json_annotation: ^4.0.1
  permission_handler: ^8.1.2

# Overriding carp libraries to use the local copy
# Remove this before release of package
#dependency_overrides:
#  carp_core:
#    path: ../../carp_core/
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  test: ^1.17.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
