name: carp_mobile_sensing_example
description: Examples of how to use the carp_mobile_sensing plugin.
publish_to: 'none'
version: 0.32.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # carp_core:
  #   path: ../../carp_core
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/

dev_dependencies:

flutter:
  uses-material-design: true
