name: carp_communication_package
description: CARP communication sampling package. Samples phone, sms, and calendar logs and activity.
version: 0.32.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_communication_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.31.0
  carp_mobile_sensing: ^0.32.0

  json_annotation: ^4.3.0
  telephony: ^0.1.4
  call_log: ^3.0.3
  device_calendar: ^4.0.1-dev.13167
  crypto: ^3.0.1
  permission_handler: ^8.3.0  
  
# Overriding carp libraries to use the local copy.
# Remove this before release of package.
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/
  
  # waiting for the device_calendar to be released in a null-safe version ... :-(
  # device_calendar:
  #   git: https://github.com/builttoroam/device_calendar.git

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any

flutter:
