name: carp_health_package_example
description: Examples of how to use the CANS Health Package.
version: 2.3.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
#  carp_core:
#    path: ../../../carp_core
#  carp_mobile_sensing:
#    path: ../../../carp_mobile_sensing
  carp_health_package:
    path: ../

flutter:
  uses-material-design: true
