name: carp_context_package_example
description: A simple example of using the CARP Context Package
publish_to: 'none' 
version: 0.33.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  # carp_core:
  #   path: ../../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_audio_package:
    path: ../

flutter:
  uses-material-design: true
