name: carp_health_package
description: CARP health sampling package. Samples health data from Apple Health or Google Fit.
version: 0.6.6
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_health_package

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  health: ^1.0.1
  #carp_mobile_sensing: ^0.6.6

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  carp_mobile_sensing:
    path: ../carp_mobile_sensing/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.0.0


# The following section is specific to Flutter.
flutter:
