name: carp_health_package
description: CARP health sampling package. Samples health data from Apple Health or Google Fit.
version: 2.1.2
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_health_package

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.31.0
  carp_mobile_sensing: ^0.31.0

  health: ^3.0.6
  json_annotation: ^4.3.0
  uuid: ^3.0.4
  meta: ^1.3.0
  permission_handler: '>=8.1.0 <8.2.0'

# Overriding carp libraries to use the local copy
# Remove this before release of package
#dependency_overrides:
#  carp_core:
#    path: ../../carp_core/
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
