name: carp_health_package
description: CARP health sampling package. Samples health data from Apple Health or Google Fit.
version: 2.0.0
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_health_package

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  health: ^3.0.6
  carp_core: ^0.30.0
  carp_mobile_sensing: ^0.30.1
  uuid: ^3.0.4
  meta: ^1.3.0
  permission_handler: ^8.1.3

# Overriding carp libraries to use the local copy
# Remove this before release of package
#dependency_overrides:
#  carp_core:
#    path: ../../carp_core/
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.4
  test: ^1.17.10


# The following section is specific to Flutter.
flutter:
