name: carp_webservices
description: Flutter API for accessing the CARP web services - authentication, file management, data points, and app-specific collections of documents.
version: 0.33.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/backends/carp_webservices

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.33.0 
  carp_mobile_sensing: ^0.33.0  

  http: ^0.13.3
  http_parser: ^4.0.0
  uuid: ^3.0.4
  json_annotation: ^4.4.0
  retry: ^3.1.0
  meta: ^1.3.0
  form_field_validator: ^1.1.0
  url_launcher: ^6.0.9


# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - asset/images/

