name: carp_core
description: The core domain model for the CARP Mobile Sensing Framework in Flutter. 
version: 0.21.4+3
homepage: https://github.com/cph-cachet/carp.sensing-flutter
author:  CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  meta: ^1.1.8
  uuid: ^2.0.0


dev_dependencies:
  pedantic: ^1.10.0        # For pedantic Dart linter
  build_runner: ^1.10.0   # For building json serialization
  json_serializable: ^3.0.0
  test: 


