name: carp_core
description: The core domain model for the CARP Mobile Sensing Framework in Flutter.
version: 0.30.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter
author:  CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  meta: ^1.3.0
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.11.0      # For pedantic Dart linter
  build_runner: ^2.0.4   # For building json serialization
  json_serializable: ^4.1.3
  test:
