name: carp_core
description: The core domain model for the CARP Mobile Sensing Framework in Flutter.
version: 0.33.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.3.0
  meta: ^1.3.0
  uuid: ^3.0.4

dev_dependencies:
  pedantic: any      # For pedantic Dart linter
  build_runner: any   # For building json serialization
  json_serializable: any
  test: any
 