name: carp_core
description: The core domain model for the CARP Mobile Sensing Framework in Flutter.
version: 0.40.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  meta: ^1.3.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any   # For building json serialization
  json_serializable: any
  flutter_lints: any
  test: any
