name: carp_core
description: The core domain model for the CARP Mobile Sensing Framework in Flutter.
version: 0.40.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: ^4.5.0
  meta: ^1.3.0
  uuid: ^3.0.4
  
dev_dependencies:
  build_runner: any   # For building json serialization
  json_serializable: any
  test: any
  lints: any
 
# auto generate json code (.g files) with:
#   flutter pub run build_runner build --delete-conflicting-outputs
