name: carp_survey_package_example
description: Examples of how to use the carp_survey_package.
version: 0.31.0
publish_to: none

environment:
  sdk: ">=2.1.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  carp_core:
#    path: ../../../carp_core
#  carp_mobile_sensing:
#    path: ../../../carp_mobile_sensing
  carp_survey_package:
    path: ../

dev_dependencies:
#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
