name: carp_esense_package
description: The CARP eSense sampling package. Samples sensor and device events from the eSense ear plug device.
version: 0.31.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_esense_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.31.0
  carp_mobile_sensing: ^0.31.0

  json_annotation: ^4.0.1
  esense_flutter: ^0.4.3
  permission_handler: '>=8.1.0 <8.2.0'

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
#  carp_core:
#    path: ../../carp_core/
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/
  # esense_flutter:
  #   path: ../../../../flutter-plugins/packages/esense_flutter/


dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.4
  test: 

# The following section is specific to Flutter.
flutter:
