name: carp_study_generator
description: Utilities for generating CARP Mobile Sensing studies
version: 0.32.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  carp_core: ^0.31.0
  carp_mobile_sensing: ^0.32.0

  carp_webservices: ^0.32.1
  carp_backend: ^0.32.1

  carp_apps_package: ^0.32.0
  carp_context_package: ^0.32.0
  carp_audio_package: ^0.32.0
  carp_esense_package: ^0.32.0
  carp_survey_package: ^0.32.0
  carp_health_package: ^2.2.0

  # cannot load communication package due to a conflict w. device_calendar plugin
  # carp_communication_package: ^0.32.0
  
  # cannot load connectivity package, due to package conflict btw. research_package 
  # and flutter_blue using different version of rxdart....
  #carp_connectivity_package: ^0.32.0

  research_package: ^0.6.4      # the informed consent domain model

  yaml: ^3.1.0
  meta: ^1.3.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/
  # carp_webservices:
  #   path: ../../backends/carp_webservices/
  # carp_backend:
  #   path: ../../backends/carp_backend/

  # carp_apps_package:
  #   path: ../../packages/carp_apps_package/
  # carp_communication_package:
  #   path: ../../packages/carp_communication_package/
  # carp_context_package:
  #   path: ../../packages/carp_context_package/
  # carp_audio_package:
  #   path: ../../packages/carp_audio_package/
  # carp_esense_package:
  #   path: ../../packages/carp_esense_package/
  # carp_survey_package:
  #   path: ../../packages/carp_survey_package/
  # carp_health_package:
  #   path: ../../packages/carp_health_package/
  
  # device_calendar:
  #   git: https://github.com/builttoroam/device_calendar.git


dev_dependencies:
  test: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
