name: carp_study_generator
description: Utilities for generating CARP Mobile Sensing studies
version: 0.30.3
homepage: https://github.com/cph-cachet/carp.sensing-flutter
author:  CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  carp_core: ^0.30.1
  carp_mobile_sensing: ^0.30.3
  carp_webservices: ^0.30.0
  carp_backend: ^0.30.3

  carp_apps_package: ^0.30.0

  # cannot load connectivity package, due to package conflict btw. research_package and flutter_blue
  # using different version of rxdart....
  #carp_connectivity_package: ^0.30.0

  carp_communication_package: ^0.30.0
  carp_context_package: ^0.30.0
  carp_audio_package: ^0.30.1
  carp_esense_package: ^0.30.0
  carp_survey_package: ^0.30.0
  carp_health_package: ^2.0.0

  research_package: ^0.6.0      # the informed consent domain model

  yaml: ^3.1.0
  meta: ^1.3.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
#  carp_core:
#    path: ../../carp_core/
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/
#  carp_webservices:
#    path: ../carp_webservices/
#  carp_backend:
#    path: ../../backends/carp_backend/


dev_dependencies:
  test: ^1.17.10
