name: carp_mobile_sensing
description: Mobile Sensing Framework for Flutter. A software framework for collecting sensor data from the phone and attached wearable devices via probes. Can be extended.
version: 0.8.5
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # utility plugins
  system_info: ^0.1.0
  uuid: ^2.0.0
  async: ^2.4.0
  device_info: '>=0.4.2 <2.0.0'
  json_annotation: ^3.0.0
  path_provider: ^1.2.0
  archive: ^2.0.4
  permission_handler: ^5.0.0
  shared_preferences: '>=0.5.7 <2.0.0'
  package_info: '>=0.4.0 <2.0.0'
  meta: ^1.1.8
  permission_handler_platform_interface: ^2.0.1

  # probe-dependent plugins
  sensors: '>=0.4.2 <2.0.0'
  battery: '>=0.3.0 <2.0.0'
  stats: ^1.0.0           # For calculating statistics, ex LightProbe

  # the CACHET plugins
  pedometer: ^1.0.0       # Get the step count from local OS
  light: ^1.0.0           # Light sensor over platform channel
  device_apps: ^1.0.8     # Device installed apps over platform channel
  screen_state: ^1.0.0    # Screen LOCK/ON/OFF
#  app_usage: ^1.0.1       # Usage of different apps

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.0.0
  test:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
