name: carp_mobile_sensing
description: Mobile Sensing Framework for Flutter. A software framework for collecting sensor data from the phone and attached wearable devices via probes. Can be extended.
version: 0.30.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter
author:  CACHET Team <cph.cachet@gmail.com>

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  #carp_core: ^0.30.0      # the core CARP domain model

  # utility plugins
  system_info: ^1.0.0
  uuid: ^3.0.4
  async: ^2.7.0
  device_info_plus: ^2.0.0
  json_annotation: ^4.0.1
  path_provider: ^2.0.2
  archive: ^3.1.2
  permission_handler: ^8.0.1
  shared_preferences: ^2.0.6
  package_info_plus: ^1.0.0
  meta: ^1.3.0
  permission_handler_platform_interface: ^3.5.1
  cron: ^0.3.0            # For scheduling / triggering cron jobs

  # probe-dependent plugins
  sensors_plus: ^1.0.0
  battery_plus: ^1.0.0
  stats: ^2.0.0           # For calculating statistics, ex LightProbe

  # the CACHET plugins
  pedometer: ^3.0.0       # Get the step count from local OS
  light: ^2.0.0           # Light sensor over platform channel
  device_apps: ^2.1.1     # Device installed apps over platform channel
  screen_state: ^2.0.0    # Screen LOCK/ON/OFF

#  collection: ^1.15.0-nullsafety.4


# Overriding carp core libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  carp_core:
    path: ../carp_core/


dev_dependencies:
  pedantic: ^1.11.0        # For pedantic Dart linter
  build_runner: ^2.0.4   # For building json serialization
  json_serializable: ^4.1.3
  test: ^1.17.5

# The following section is specific to Flutter.
flutter:

