name: carp
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  carp_mobile_sensing: ^0.21.0
  carp_context_package: ^0.21.0
  carp_survey_package: ^0.21.0
  carp_audio_package: ^0.21.0
  carp_backend: ^0.21.0
  #carp_communication_package: ^0.6.1
  #carp_health_package: ^0.6.1
  research_package: ^0.5.3


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
