# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

name: carp_audio_package
description: CARP Audio Sampling Package. Samples audio recording and noise.
version: 0.30.5
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_audio_package

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  carp_core: ^0.30.1
  carp_mobile_sensing: ^0.30.5
  flutter_sound: ^8.1.4   # audio probe
  noise_meter: ^3.0.1     # measuring noise level
  path_provider: ^2.0.2
  stats: ^2.0.0
  permission_handler: ^8.1.1

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  test: 

# The following section is specific to Flutter.
flutter:
