name: carp_audio_package
description: CARP Audio Sampling Package. Samples audio recording and noise.
version: 0.31.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_audio_package

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
    
  carp_core: ^0.31.0
  carp_mobile_sensing: ^0.31.0
  json_annotation: ^4.0.1
  permission_handler: '>=8.1.0 <8.2.0'
  flutter_sound: ^8.1.4   # audio probe
  noise_meter: ^3.0.3     # measuring noise level
  stats: ^2.0.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  test: 

# The following section is specific to Flutter.
flutter:
