name: carp_backend
description: CARP data backend for CARP mobile sensing. Supports uploading json to CARP as either zipped filed or as plain json in collections.
version: 0.30.5
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/backends/carp_backend
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  json_annotation: ^4.0.1
  carp_core: ^0.30.1
  carp_mobile_sensing: ^0.30.5
  carp_webservices: ^0.30.1
  research_package: ^0.6.4      # the informed consent domain model


# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/
  # carp_webservices:
  #   path: ../carp_webservices/
#  research_package:
#    path: ../../../../research.package/
  # the following sampling packages are only used for unit testing
#  carp_esense_package:
#    path: ../../packages/carp_esense_package/
#  carp_audio_package: 
#    path: ../../packages/carp_audio_package/
#  carp_context_package:
#    path: ../../packages/carp_context_package/


dev_dependencies:
  build_runner: ^2.1.0       # used to build JSON serialization .g files
  json_serializable: ^4.1.4
  test: ^1.17.10

# The following section is specific to Flutter.
flutter:
